# use the official node docker file
FROM node:20.0.0-alpine AS build

# set the working directory
WORKDIR /app

# copy the package.json file to the working directory
COPY aespa/package.json .
COPY aespa/package-lock.json .

# install dependencies
RUN npm install

# copy the rest of the files to the working directory
COPY aespa/. .
